services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
    image: my-todos-web:latest
    container_name: my-todos-web
    ports:
      - "8080:80"

  db:
    image: mysql:8.4
    container_name: my-todos-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: ./api
    image: my-todos-api:latest
    container_name: my-todos-api
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./api/src:/app/src
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

  phpmyadmin:
    image: phpmyadmin:5
    container_name: my-todos-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  mysql_data:
